### PR TITLE
Import pools using the lvs implementation and associated cleanup

### LINKED ISSUE #454: Destroying a pool created via yaml config results in "thread 'main' panicked"
**Describe the bug**
Destroying a pool created via yaml config results in "thread 'main' panicked" though the Mayastor process remains running and usable.

**To Reproduce**
1. Create a file as a backing store for the pool:
```
truncate -s 128M /tmp/pool0.img
```
2. Create a Mayastor config and save it as pool.yaml:
```
---
pools:
  - name: pool0
    disks:
      - /tmp/pool0.img
    blk_size: 512
    io_if: 0
    replicas:
      - name: 00000000-1234-abcd-cdef-012345678901
        share: ~
implicit_share_base: true
sync_disable: true
```
3. Start Mayastor:
```
# mayastor -g 127.0.0.1:10124 -y pool.yaml
```
4. Verify the pool exists, then delete it:
```
$ mayastor-client pool list
NAME  STATE   CAPACITY USED DISKS
pool0 online 130023424    0      

$ mayastor-client pool destroy pool0
Error: Status { code: Unknown, message: "transport error: http2 error: protocol error: stream no longer needed" }
```
5. Note the panic in the Mayastor log:
```
2020-10-02T16:33:54.457261484+01:00  INFO mayastor::subsys::config: creating pool pool0
2020-10-02T16:33:54.457429219+01:00  INFO mayastor::pool: aio bdev /tmp/pool0.img was created
2020-10-02T16:33:54.459128346+01:00  INFO mayastor::pool: The pool pool0 has been created
2020-10-02T16:33:54.459237551+01:00  INFO mayastor::subsys::config: creating nexus devices
2020-10-02T16:33:54.459563656+01:00  INFO mayastor::grpc::server: gRPC server configured at address 127.0.0.1:10124
2020-10-02T16:33:54.459726049+01:00  INFO mayastor::core::reactor: core 0 set to developer delayed poll mode
2020-10-02T16:33:54.460933198+01:00  INFO mayastor: Mayastor started 🚀 ...
2020-10-02T16:33:59.027100971+01:00  INFO mayastor::lvs::lvs_pool: pool pool0 destroyed successfully
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', mayastor/src/lvs/lvs_pool.rs:491:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
At this point Mayastor is still usable and you can still create and delete pools.

**Expected behavior**
Not panic when deleting a pool.

**OS info**
 - Distro: Ubuntu 20.04
 - Kernel version 5.4.0-42-generic
 - MayaStor develop branch commit ce9246e84915f417478265b0c91cd601d669f13e

**Additional context**
If the pool was created was creating using gRPC, the panic does not occur as that uses the new pool API at `mayastor::lvs::lvs_pool` instead of `mayastor::pool` used by the yaml config import code.

### PR DESCRIPTION
**Pull request by jonathan-teh**
This makes it consistent with the destroy path, addressing the panic in #454. Remove block_size and io_if from CreatePoolRequest as they were ignored anyway in favour of encoding them within the URI in the disks field.

Fixes #454, fixes CAS-455.

### CODE REVIEW

**Review by gila — APPROVED** [review]
Could we also clean up replica.rs with this commit?

**Comment by jonathan-teh** [comment]
> Could we also clean up replica.rs with this commit?

I did make a start but it started to get a bit large so I drew a line there. I guess you're happy to have this done in the same PR so I'll carry on.

File: mayastor-test/test_replica.js [hunk 1]
```diff
@@ -161,9 +160,9 @@ describe('replica', function () {
 
   it('should not create a pool with invalid block size', (done) => {
     client.createPool(
-      { name: POOL, disks: disks, block_size: 1238513 },
+      { name: POOL, disks: disks.map((d) => `${d}?blk_size=1238513`) },
       (err) => {
-        assert.equal(err.code, grpc.status.INVALID_ARGUMENT);
+        assert.equal(err.code, grpc.status.INTERNAL);
```
Comment (jkryl) [inline mayastor-test/test_replica.js:165]: Is there a chance that we could preserve invalid_argument error that is better fit than internal error for the case of invalid block size specification?

File: mayastor/tests/pool.rs [hunk 2]
```diff
@@ -1,150 +0,0 @@
...
-                    assert_eq!(pools.len(), 2);
-                    for p in pools {
-                        p.destroy().await.unwrap();
-                    }
-                });
-
-                mayastor_env_stop(0);
-            })
-            .unwrap();
-    });
```
Comment (jkryl) [inline mayastor/tests/pool.rs:146]: do we have a replacement for this test for the new bits? We should make sure that this scenario is still covered by the tests.

**Review by jkryl — COMMENTED** [review]
Thanks for the cleanup!

**Review by paulyoong — APPROVED** [review]

File: mayastor/tests/pool.rs (hunk 2 above)
Comment (jonathan-teh) [reply mayastor/tests/pool.rs:146]: Yes, lvs_pool_test uses the newer Lvs API.

File: mayastor-test/test_replica.js (hunk 1 above)
Comment (jonathan-teh) [reply mayastor-test/test_replica.js:165]: Yes, but create_or_import was simply enforcing a 0/512/4096 value on the block_size field, and returning INVALID_ARGUMENT otherwise, but it was actually using blk_size encoded in the URL so enforcement was happening in the bdev module so any error from there becomes INTERNAL.

File: mayastor/src/lvs/lvs_pool.rs [hunk 3]
```diff
@@ -299,27 +300,21 @@ impl Lvs {
...
-
-        // fixup the device uri's to URL
+        // default to uring if kernel supports it
         let disks = args
             .disks
             .iter()
             .map(|d| {
-                if d.starts_with("/dev") {
-                    format!("aio://{}", d)
+                if Url::parse(d).is_err() {
```
Comment (tiagolobocastro) [inline mayastor/src/lvs/lvs_pool.rs:308]: do we still need to support this "legacy"?

**Review by tiagolobocastro — APPROVED** [review]

File: mayastor/src/lvs/lvs_pool.rs (hunk 3 above)
Comment (jonathan-teh) [reply mayastor/src/lvs/lvs_pool.rs:308]: This maintains the existing "auto" setting of io_if and allows existing yaml config files to work.

**Review by jkryl — APPROVED** [review]

**Comment by jonathan-teh** [comment]
bors merge

**Comment by jonathan-teh** [comment]
bors merge
