### PR TITLE
default to zero upon failed hugepages lookups

### LINKED ISSUE #1273: Mayastor IO Engine pods fail to boot due to grpc client connection error
**Describe the bug**
While attempting to install mayastor `2.0.0-develop` via the helm chart, everything works except for the `mayastor-io-engine` pods, which appear to have an issue with the grpc client:

```
  2022-12-26T22:45:29.485461Z ERROR exporter::pool::client::grpc_client: Grpc client connection error, retrying after 10s, error: transport error
    at exporter/src/pool/client/grpc_client.rs:122
```

Happy to grab more logs somewhere though I'm at a loss of where to look for anything that might be more helpful. I thought perhaps it might be a networking issue (i.e. something about [the ports](https://mayastor.gitbook.io/introduction/v/develop/quickstart/prerequisites#networking-requirements) being used) but nothing else is running on the cluster. Perhaps there is a permission/rbac config missing that isn't already installed by helm?

**To Reproduce**
Deploy mayastor via the `develop` docs [here](https://mayastor.gitbook.io/introduction/v/develop/quickstart/preparing-the-cluster) using helm.

**Expected behavior**
Should see all Running pods in `kubectl get pods -n mayastor` after install.

**Screenshots**

Screenshot 2022-12-26 at 3 42 50 PM

Screenshot 2022-12-26 at 3 42 27 PM

Screenshot 2022-12-26 at 3 43 21 PM

** OS info (please complete the following information):**

Distro: Talos Linux v1.3.0
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.25.2
MayaStor revision or container image: 2.0.0-develop

**Additional context**
Note that Mayastor 1.0 was working just fine on this cluster. I removed all mayastor 1.0 components and am attempting to install 2.0.

### PR DESCRIPTION
**Pull request by hiattp**
Closes #1273

### CODE REVIEW

File: io-engine/src/bin/io-engine.rs [hunk 1]
```diff
@@ -92,10 +92,29 @@ fn start_tokio_runtime(args: &MayastorCliArgs) {
...
 
 fn hugepage_get_nr(hugepage_path: &Path) -> (u32, u32) {
-    let nr_pages: u32 = sysfs::parse_value(hugepage_path, "nr_hugepages")
-        .expect("failed to read the number of pages");
-    let free_pages: u32 = sysfs::parse_value(hugepage_path, "free_hugepages")
-        .expect("failed to read the number of free pages");
+    let nr_pages: u32 = match sysfs::parse_value(hugepage_path, "nr_hugepages") {
+        Ok(c) => c,
+        Err(e) => {
+            log::error!(
```
Comment (tiagolobocastro) [inline io-engine/src/bin/io-engine.rs]:
```suggestion
            error!(
```
To use the `tracing` instead of `log` crate.
Also, should this be a warning since we're defaulting to 0 and check the `PAGES_NEEDED` anyway?

Comment (hiattp) [reply io-engine/src/bin/io-engine.rs]: Makes sense to me 👍

Comment (hiattp) [reply io-engine/src/bin/io-engine.rs]: Updated to a `warn!`

**Comment by tiagolobocastro** [comment]
@hiattp your commit must follow conventional commit, example: `fix: default to zero upon failed hugepages lookups`
Also please sign your commit, eg `git commit --amend -s`
thank you

File: io-engine/src/bin/io-engine.rs [hunk 2]
```diff
@@ -92,10 +92,29 @@ fn start_tokio_runtime(args: &MayastorCliArgs) {
...
+        Ok(c) => c,
+        Err(e) => {
+            warn!(
+                "failed to read the number of pages at {}: {}", hugepage_path.display(), e
+            );
+            // NOTE: We check for 1g pages but the directory for 1g pages won't exist if they are
+            // not enabled. Effectively this means that zero 1g hugepages are available, so it
+            // seems sensible to fall back to 0 if reads fail. See discussion here:
+            // https://github.com/openebs/mayastor/issues/1273.
+            return 0;
```
Comment (tiagolobocastro) [inline io-engine/src/bin/io-engine.rs]:
```suggestion
            return (0, 0);
```

File: io-engine/src/bin/io-engine.rs [hunk 3]
```diff
@@ -92,10 +92,29 @@ fn start_tokio_runtime(args: &MayastorCliArgs) {
...
+        },
+    };
+
+    let free_pages: u32 = match sysfs::parse_value(hugepage_path, "free_hugepages") {
+        Ok(c) => c,
+        Err(e) => {
+            warn!(
+                "failed to read the number of free pages at {}: {}", hugepage_path.display(), e
+            );
+            return 0;
```
Comment (tiagolobocastro) [inline io-engine/src/bin/io-engine.rs]:
```suggestion
            0
```

File: io-engine/src/bin/io-engine.rs (hunk 2 above)
Comment (hiattp) [reply io-engine/src/bin/io-engine.rs]: Good catch, though I suppose this could just be `0` instead of a return? Might as well attempt the free pages lookup in case the error is not a completely missing directory.

**Comment by hiattp** [comment]
> @hiattp your commit must follow conventional commit, example: `fix: default to zero upon failed hugepages lookups` Also please sign your commit, eg `git commit --amend -s` thank you

Sounds good will do

File: io-engine/src/bin/io-engine.rs (hunk 2 above)
Comment (tiagolobocastro) [reply io-engine/src/bin/io-engine.rs]: Yes could be, though chances are it will be non-existent too. I've got no strong preference here so I'll leave it up to you :)

**Comment by hiattp** [comment]
@tiagolobocastro Back to you 👍

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro Back to you +1

Still missing the signoff: https://github.com/openebs/mayastor/pull/1284#issuecomment-1386502466

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
@hiattp please also lint the rust code using `./scripts/rust-style` and `./scripts/rust-linter.sh`.

**Review by dsavitskiy — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@hiattp if you're busy shall I take over this, would be good for this to make it into 2.0
Please let me know, thanks!

**Comment by hiattp** [comment]
Hey @tiagolobocastro yes unfortunately got busy and won’t have time to revisit for a couple of weeks yet. Feel free to take over if needed. Thanks!

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> Hey @tiagolobocastro yes unfortunately got busy and won’t have time to revisit for a couple of weeks yet. Feel free to take over if needed. Thanks!

No problem, thanks for coming back so quick!
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
@hiattp seems I cannot merge this due to github's vigilant mode. I even tried writing a new commit and add co-auth by you even that doesn't work.
It still complains with "This commit is not signed, but one or more authors requires that any commit attributed to them is signed. "

If you know how to resolve this please do, otherwise I'll merge with the "co-auth in quotes"

**Comment by hiattp** [comment]
@tiagolobocastro Nope feel free to attribute in quotes, or leave me out altogether, whatever is easiest for you 👍

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro Nope feel free to attribute in quotes, or leave me out altogether, whatever is easiest for you +1

I'll leave you in quotes :) 
bors merge

**Comment by tiagolobocastro** [comment]
bors merge
