### PR TITLE
fix(nexus): assertion failure when unpublishing a faulted nexus

### LINKED ISSUE #549: Assertion failure when unpublishing or destroying a nexus in faulted state
**Describe the bug**
Mayastor fails an assertion when attempting to destroy a nexus that is in the faulted state:
```
mayastor: subsystem.c:465: nvmf_subsystem_set_state: Assertion `actual_old_state == expected_old_state' failed.
```

**To Reproduce**
Create a nexus with 1 child being a remote replica served by an nvmf target, i.e.:
```
$ mayastor-client nexus list -c
NAME                                 PATH                                                                                        SIZE STATE  REBUILDS CHILDREN                                                                         
5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391 nvmf://127.0.0.1:8430/nqn.2019-05.io.openebs:nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391 60000000 online        0 nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391
```
Publish the nexus over nvmf, connect to it with the kernel NVMe initiator and send IO e.g. with `fio`.
Make the nvmf target serving the replica inaccessible. In this case, sending `SIGSTOP` to that mayastor instance.

The mayastor instance serving the nexus detects a timeout:
```
[2020-12-01T17:54:24.942056536+00:00  WARN mayastor::spdk:bdev_nvme.c:1149] Warning: Detected a timeout. ctrlr=0x557ec85b6d70 qpair=(nil) cid=2 
```
and eventually notices that a reset is required:
```
[2020-12-01T17:56:29.874237303+00:00 ERROR mayastor::spdk:bdev_nvme.c:1153] Controller Fatal Status, reset required   
[2020-12-01T17:56:34.872024397+00:00  WARN mayastor::spdk:bdev_nvme.c:1149] Warning: Detected a timeout. ctrlr=0x557ec85b6d70 qpair=(nil) cid=27   
```
At this point, send `SIGCONT` to the mayastor instance serving the replica.
Back at the other mayastor instance, the (only) child is faulted:
```
[2020-12-01T17:57:50.724579130+00:00 ERROR mayastor::bdev::nexus::nexus_io:nexus_io.rs:319] name: 127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391n1, driver: nvme, product: NVMe disk, num_blocks: 122880, block_len: 512
[2020-12-01T17:57:50.724733805+00:00  WARN mayastor::bdev::nexus::nexus_io:nexus_io.rs:329] core 0 thread Some(Mthread(0x557ec7c83090)), faulting child nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: Faulted(IoError), blk_cnt: 122880, blk_size: 512
```
Network errors are logged:
```
[2020-12-01T17:57:50.825560183+00:00 ERROR mayastor::spdk:posix.c:171] getpeername() failed (errno=107)   
[2020-12-01T17:57:50.825668020+00:00 ERROR mayastor::spdk:tcp.c:958] spdk_sock_getaddr() failed of tqpair=0x557ec85d5fa0   
```
and the nexus is reconfigured to fault the child and remove it from the nexus:
```
[2020-12-01T17:57:50.844321020+00:00  INFO mayastor::bdev::nexus::nexus_bdev:nexus_bdev.rs:454] nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: Dynamic reconfiguration event: ChildFault started
[2020-12-01T17:57:50.844403241+00:00  INFO mayastor::bdev::nexus::nexus_channel:nexus_channel.rs:102] nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391(thread:"mayastor_nvmf_tcp_pg_core_0"), refreshing IO channels
[2020-12-01T17:57:50.845618145+00:00  INFO mayastor::bdev::nexus::nexus_channel:nexus_channel.rs:244] nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: Reconfigure completed
[2020-12-01T17:57:50.846884423+00:00  INFO mayastor::bdev::nexus::nexus_bdev:nexus_bdev.rs:468] nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: Dynamic reconfiguration event: ChildFault completed 0
```
The child removal is complete:
```
[2020-12-01T17:57:50.847500441+00:00 ERROR mayastor::bdev::nexus::nexus_io:nexus_io.rs:344] :nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: state: Mutex { data: Open } blk_cnt: 112607, blk_size: 512
        nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391: Faulted(IoError), blk_cnt: 122880, blk_size: 512
 has no children left... 
[2020-12-01T17:57:50.847578102+00:00  INFO mayastor::core::bdev:bdev.rs:168] Received remove event for bdev 127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391n1
[2020-12-01T17:57:50.847634549+00:00  INFO mayastor::bdev::nexus::nexus_child:nexus_child.rs:367] Removing child nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391
[2020-12-01T17:57:50.847766549+00:00  INFO mayastor::bdev::nexus::nexus_child:nexus_child.rs:405] Child nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391 removed
```
However, the replica is still listed as a child in the nexus:
```
$ mayastor-client nexus list -c
NAME                                 PATH                                                                                        SIZE STATE   REBUILDS CHILDREN                                                                         
5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391 nvmf://127.0.0.1:8430/nqn.2019-05.io.openebs:nexus-5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391 60000000 faulted        0 nvmf://127.0.0.1:8420/nqn.2019-05.io.openebs:5b5b04ea-c1e3-11ea-bd82-a7d5cb04b391
```
but when you try to destroy the nexus mayastor fails an assertion:
```
mayastor: subsystem.c:465: nvmf_subsystem_set_state: Assertion `actual_old_state == expected_old_state' failed.
```
where the assertion is [here](https://github.com/openebs/spdk/blob/v20.10.x-mayastor/lib/nvmf/subsystem.c#L465).

**Expected behavior**
The nexus should be destroyed.

**Screenshots**
** OS info:**
 - Distro: Ubuntu 20.04
 - Kernel 5.4.0-56-generic
 - Mayastor 0.6

**Additional context**
Developer debug build.

### PR DESCRIPTION
**Pull request by jonathan-teh**
The assertion occurs due to the nvmf subsystem transitioning from a
paused to an inactive state, which is forbidden. Always resume the
nexus in child_retire so that it is usually in the active state, which
avoids the assertion when unpublishing it.

Fixes #549, CAS-549, CAS-606.

### CODE REVIEW

**Comment by jonathan-teh** [comment]
bors try

File: mayastor/tests/replica_timeout.rs [hunk 1]
```diff
@@ -1,23 +1,33 @@
...
 pub mod common;
 static NXNAME: &str = "nexus";
 
-#[ignore]
 #[tokio::test]
 async fn replica_stop_cont() {
+    // Use a shorter timeouts than the default to reduce test runtime
+    Config::get_or_init(|| Config {
+        nvme_bdev_opts: NvmeBdevOpts {
+            action_on_timeout: 2,
```
Comment (chriswldenyer) [inline mayastor/tests/replica_timeout.rs:19]: Should we be explicitly setting action_on_timeout?
The default is already 2 (== SPDK_BDEV_NVME_TIMEOUT_ACTION_ABORT) and maybe we should be testing the default behaviour. Otherwise we should comment what 2 means.

**Review by chriswldenyer — APPROVED** [review]
LGTM but see comment. Maybe mention in the description that the timeout test is back in action.

File: mayastor/src/bdev/nexus/nexus_io.rs [hunk 2]
```diff
@@ -338,9 +338,8 @@ impl Bio {
                     nexus.reconfigure(DREvent::ChildFault).await;
                     //nexus.remove_child(&uri).await.unwrap();
                     bdev_destroy(&uri).await.unwrap();
-                    if nexus.status() != NexusStatus::Faulted {
-                        nexus.resume().await.unwrap();
-                    } else {
+                    nexus.resume().await.unwrap();
```
Comment (mtzaurus) [inline mayastor/src/bdev/nexus/nexus_io.rs:341]: Could you please add comments with explanation why it's safe to always unconditionally resume Nexus even if it's (potentially) in Faulted state ? At the first glance eliminating check against NexusStatus::Faulted looks strange, as this state means exactly "no I/O to the Nexus, please":

```
pub enum NexusStatus {
    /// The nexus cannot perform any IO operation
    Faulted,
    /// Degraded, one or more child is missing but IO can still flow
    Degraded,
    /// Online
    Online,
}
```

File: mayastor/tests/replica_timeout.rs (hunk 1 above)
Comment (jonathan-teh) [reply mayastor/tests/replica_timeout.rs:19]: Good points, I don't remember why I explicitly set it to the (current) default. I'll drop it.

File: mayastor/src/bdev/nexus/nexus_io.rs (hunk 2 above)
Comment (jonathan-teh) [reply mayastor/src/bdev/nexus/nexus_io.rs:341]: I've updated the code comments for the subsystem pause/resume functions. SPDK considers these to be synchronisation primitives so pause is intended to be temporary.

Comment (mtzaurus) [reply mayastor/src/bdev/nexus/nexus_io.rs:341]: I see, thanks.

**Review by mtzaurus — APPROVED** [review]

File: mayastor/src/bdev/nexus/nexus_bdev.rs [hunk 3]
```diff
@@ -820,6 +826,22 @@ impl Nexus {
         }
     }
 
+    /// check results after submitting IO, failing if all failed to submit
+    fn check_io_submission(&self, results: &[i32], io: &Bio) {
```
[the remark this answers is not in the document]
Comment (jonathan-teh) [reply mayastor/src/bdev/nexus/nexus_bdev.rs:831]: Done. At some point we may want to revisit this, and the hot path in general, as the compiler, surprisingly, generates a forward jump over the error logging (Rust hasn't implement likely/unlikely intrinsics yet) so we could move that into a separate non-inlined function to reduce bloat.

**Comment by jonathan-teh** [comment]
bors merge
